Lesson 10
wrongbees/TestRail pull request #1
Opened 2021-07-11 22:53 UTC by wrongbees

2021-07-12 16:15 UTC, wildpioneer requested changes

2021-07-12 16:15 UTC, wildpioneer commented on src/test/java/data/StaticProvider.java
> +                {"Lesson10_Privet_06onl","Title","Preconditions","Steps","ExpectedResult"}
Пробелы между значениями - читать будет легче

2021-07-12 16:15 UTC, wildpioneer commented on src/test/java/pages/EditTestCasePage.java
> +public class EditTestCasePage extends BasePage {
На странице Add и Edit для TestCases много общих элементов - в таком случае, надо делать одну базовую страницу для них. На занятии объясню.

2021-07-12 16:15 UTC, wildpioneer commented on src/test/java/steps/AddTestCaseStep.java
> +public class AddTestCaseStep extends BaseStep {
Все Steps связанные с работой с TestCases должны находиться в одном файле - в этом как раз и суть общих степов по единой функциональности -  на занятии объясню.

2021-07-12 16:15 UTC, wildpioneer commented on src/test/java/tests/AddEditDeleteCasesSmokeTests.java
> +        Thread.sleep(500);// иногда без сна не прогружается элемент использующийся в следующей строке
Значит не верно выбран элемент для определения что страница загружена.

2021-07-12 16:15 UTC, wildpioneer commented on src/test/java/tests/AddEditDeleteCasesSmokeTests.java
> +        new LoginStep(driver);
Не совсем понимаю зачем здесь 5 созданий объектов без присвоения переменным

2021-07-12 17:31 UTC, wrongbees commented on src/test/java/tests/AddEditDeleteCasesSmokeTests.java
> +        new LoginStep(driver);
В конструкторе степа вызывается метод, выполняющий последовательность действий степа.

2021-07-19 12:31 UTC, wildpioneer commented
Проверено и обсуждено

2021-07-19 12:31 UTC, closed without merging